# Install pakcages

In [1]:
!pip install pymysql    # mysql 연동을 위한 패키지
!pip install psycopg2   # postgresql 연동을 위한 패키지, 패키지 에러가 나면 psycopg2-binary로 설치
!pip install sqlalchemy # sqlalchemy 설치를 위한 패키지
!pip install pymongo    # mongodb 연동을 위한 패키지

Defaulting to user installation because normal site-packages is not writeable

ERROR: Invalid requirement: '#'

Defaulting to user installation because normal site-packages is not writeable

ERROR: Invalid requirement: '#'

Defaulting to user installation because normal site-packages is not writeable

ERROR: Invalid requirement: '#'

Defaulting to user installation because normal site-packages is not writeable

ERROR: Invalid requirement: '#'

In [ ]:
import warnings
warnings.filterwarnings('ignore')

from tqdm import tqdm

import psycopg2
import pymysql
import pymongo
import pandas as pd

from sqlalchemy import create_engine

# DataBase

## MongoDB

비관계형 데이터베이스 관리 시스템(DBMS)으로 No-SQL의 한 종류 <br>
아래의 특징 존재 
1. 문서 지향 데이터베이스
데이터를 문서 형태로 저장 <br>
문서는 json 형식으로 저장
문서 기반 저장 방식은 데이터의 중첩 및 계층적 구조 지원
2. 스키마 유연성
schema-less 데이터베이스로, 데이터 모델이 유연하고 스키마를 사전에 정의할 필요 없음 <br>
각 문서는 다른 구조를 가질 수 있어 데이터 모델링이 더 유연 <br>
3. 확장성
수평적 확장을 지원하여, 데이터 샤딩(sharding)을 통해 대량의 데이터를 여러 서버에 분산하여 저장 가능 <br>

<br>

mongo compass
- MongoDB 데이터를 쿼리, 최적화 및 분석할 수 있는 무료 대화형 도구
- 중요한 인사이트을 찾아내고, 드래그 앤 드롭으로 파이프라인을 구축하는 등 여러 가지 기능을 제공. <br>
- link: https://www.mongodb.com/products/tools/compass

### 기본 커맨드

접속
```
bash     # 1
mongosh  # 2
```
<br>

종료
```
quit
```
<br>

DB 조회
```
show databases;
```
<br>

유저 조회
```
show users;
```  
<br>

테이블 조회
```
show collections;
```
<br>

테이블 접근
```
db.*collection name*
```

### collection 커맨드

생성: 별도의 생성 커맨드 없이 데이터 삽입 시 자동 생성
```
db.*collection name*.insertOne({ name: "Alice", age: 30 });
```
<br>

삭제
```
db.*collection name*.drop();
```
<br>

### CRUD

<span style="font-size: 18px;">Create</span>

```bash
# 단일 문서 삽입
db.*collection_name*.insertOne({
    name: "Alice",
    age: 30
});

# 여러 문서 삽입
db.*collection_name*.insertMany([
    { name: "Bob", age: 25 },
    { name: "Charlie", age: 35 }
]);
```

<br>

<span style="font-size: 18px;">Read</span>

```bash
# 특정 조건에 맞는 문서 조회
db.*collection_name*.find({ name: "Alice" });

# 첫 번째 일치 문서 조회
db.*collection_name*.findOne({ name: "Alice" });
```

<br>

<span style="font-size: 18px;">Update</span>

```bash
# 단일 문서 업데이트
db.*collection_name*.updateOne(
    { name: "Alice" },
    { $set: { age: 31 } }
);

# 여러 문서 업데이트
db.*collection_name*.updateMany(
    { age: { $lt: 30 } },
    { $set: { status: "young" } }
);
```

<br>

<span style="font-size: 18px;">Delete</span>

```bash
# 단일 문서 삭제
db.*collection_name*.deleteOne({ name: "Alice" });

# 여러 문서 삭제
db.*collection_name*.deleteMany({ age: { $lt: 30 } });
```

### 유저 커맨드

user 관리는 admin db에서 진행

```bash
use admin
```

<br>

<span style="font-size: 18px;">유저 생성</span>

```bash
db.createUser({
    user: "*user_name*",
    pwd: "*user_password*",
    roles: [
        { role: "readWrite", db: "*db_name*" },
        { role: "dbAdmin", db: "*db_name*" }
    ]
});
```

<br>

roles: 사용자의 역할 및 권한 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;readWrite: DB 읽기 및 쓰기 권한 부여 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dbAdmin: DB 관리 작업을 수행 권한 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;db: 권한을 부여할 데이터베이스 <br>

<br>

<span style="font-size: 18px;">유저 정보 변경</span>

```bash
db.updateUser("*user_name*", {
    pwd: "new_password",
    roles: [
        { role: "readWrite", db: "*db_name*" },
        { role: "dbAdmin", db: "*db_name*" }
    ]
});
```

<br>

<span style="font-size: 18px;">유저 삭제</span>

```bash
db.dropUser("*user_name*");
```

### 쿼리 연산자 및 필터

```bash
$eq: 일치하는 문서 찾기
$ne: 일치하지 않는 문서 찾기
$gt: 지정된 값보다 큰 값 찾기
$lt: 지정된 값보다 작은 값 찾기
$gte: 지정된 값보다 크거나 같은 값 찾기
$lte: 지정된 값보다 작거나 같은 값 찾기
$in: 배열 내의 값 중 하나와 일치하는 문서 찾기
$and: 여러 조건을 만족하는 문서 찾기
$or: 여러 조건 중 하나를 만족하는 문서 찾기
```

<br>

<span style="font-size: 18px;">Example</span>

```bash
// age가 25 이상 35 이하인 문서 찾기
db.*collection_name*.find({
    age: { $gte: 25, $lte: 35 }
});

// age가 25 미만 또는 35 초과인 문서 찾기
db.*collection_name*.find({
    $or: [
        { age: { $lt: 25 } },
        { age: { $gt: 35 } }
    ]
});
```

### 문자열 관련 쿼리

<span style='font-size: 18px'> Exact Matching </span>

```bash
db.*collection_name*.find({ name: "Alice" });
```

<br>

<span style='font-size: 18px'> Regex </span>

```bash
db.*collection_name*.find({ name: { $regex: "Alice" } });   # name에 Alice가 포함된 document
db.*collection_name*.find({ name: { $regex: "alice", $options: "i" } });  # name에 alice가 포함된 document인데 대소문자 구분 없음
db.*collection_name*.find({ name: { $regex: "^Alice" } });  # name이 Alice로 시작하는 document
db.*collection_name*.find({ name: { $regex: "Alice$" } });  # name이 Alice로 끝나는 document
db.*collection_name*.find({ $expr: { $gt: [{ $strLenCP: "$name" }, 5] } }); # name의 길이가 5보다 큰 document
```

### 집계함수

파이프라인 방식으로 집계함수가 동작하며, 각 파이프라인 단계는 문서를 변형하거나 필터링하는 작업을 수행 <br>
각 단계의 출력은 다음 단계의 입력으로 사용 <br>

```bash
$match: 조건에 맞는 문서를 필터링           # where
$group: 문서를 그룹화하고 집계 함수를 적용    # gropuby
$sort: 문서를 정렬                       # sort
$project: 문서의 필드를 포함하거나 제외      # select
$limit: 문서 수 제한                    # limit
$skip: 문서 스킵                        # offset
$lookup: 다른 컬렉션과 조인               # join
```

<br>

<span style='font-size: 18px'> Example </span>

```bash
db.*collection_name*.aggregate([
    { $match: { age: { $gte: 25 } } },
    { $group: { _id: "$department", totalSalary: { $sum: "$salary" } } },
    { $sort: { totalSalary: -1 } }
]);
```

#### match

문서의 특정 조건을 만족하는 문서만 선택

```bash
db.*collection_name*.aggregate([
    { $match: { age: { $gte: 25 } } }
]);
```

<br>

#### group

문서를 그룹화하고 집계 함수를 적용합니다

```bash
db.*collection_name*.aggregate([
    { $group: { _id: "$department", totalSalary: { $sum: "$salary" } } }
]);
```

#### sort

문서 정렬

```bash
db.*collection_name*.aggregate([
    { $sort: { age: -1 } }  # (1: 오름차순, -1: 내림차순)
]);
```

#### project

문서에서 특정 필드만 포함하거나 제외

```bash
db.*collection_name*.aggregate([
    { $project: { name: 1, age: 1, _id: 0 } }
]);
```

#### limit

문서 출력 수 제한

```bash
db.*collection_name*.aggregate([
    { $limit: 10 }
]);
```

#### skip

문서 수를 건너 뜀 (n개 document 이후 나머지 문서 반환)

```bash
db.*collection_name*.aggregate([
    { $skip: 5 }
]);
```

#### lookup

다른 컬렉션과 조인

```bash
db.orders.aggregate([
    { $lookup: {
        from: "products",
        localField: "productId",
        foreignField: "_id",
        as: "productDetails"
    } }
]);
```

<br>

orders 컬렉션의 productId 필드를 products 컬렉션의 _id 필드와 join 후 <br>
productDetails 필드에 결과를 포함

## Database Link in Python

### psycopg2

설치
```cmd
pip install psycopg2
pip install psycopg2-binary #위의 설치 에러 시 이 코드 실행
```
<br>

사용법
```python
conn = psycopg2.connect(
  host='address',
  dbname='database name',
  user='user name',
  password='password',
  port=port
)

cur = conn.cursor()
```

<br>

CRUD
```python
cur.execute(f'INSERT INTO test (id, press_name) VALUES ({id}, {press_name});')
conn.commit() # CREATE

cur.execute('SELECT * FROM test;')
result_one = cur.fetchone() # READ
result_many = cur.fetchmany() 
result_all = cur.fetchall() 

cur.execute(f'UPDATE test SET press_name={press_name} WHERE id > 5')
conn.commit() # UPDATE

cur.execute('DELETE FROM test WHERE press_name LIKE %조선%;')
conn.commit() # DELETE
```
<br>

pandas 내의 method를 통해서도 사용 가능
```python
pd.read_sql('SELECT * FROM test', conn)
```
<br>

Closer <br>
사용 후 연결 해제 <br>
```python
conn.close()
```
<br>

아래와 같이 사용 가능
```python
with conn.cursor() as cur:
  cur.execute(query)

conn.close()

with psycopg2.connect():
  with conn.cursor() as cur:
    cur.execute(query)
```

In [3]:
import psycopg2

In [32]:
conn = psycopg2.connect(
    host='localhost',
    dbname='postgres',
    user='postgres',
    password='1234',
    port=5432,
)

In [33]:
cur = conn.cursor()

In [ ]:
# Create
cur.execute("INSERT INTO news_id (news_id, press_name) VALUES (6, '한겨레')")
conn.commit()

In [22]:
# Read
cur.execute("SELECT * FROM news_id")
result_all = cur.fetchall()

In [23]:
result_all

[('３', '동앙일보'), ('４', '연합뉴스'), ('２', '중앙일보'), ('１', '조선일보'), ('6', '한겨레')]

In [34]:
# Update
cur.execute("UPDATE news_id SET press_name='매일경제' WHERE news_id='6'")
conn.commit()

In [35]:
# Delete
cur.execute("DELETE FROM news_id WHERE news_id='6'")
conn.commit()

In [36]:
conn = psycopg2.connect(
    host='localhost',
    dbname='postgres',
    user='postgres',
    password='1234',
    port=5432,
)

with psycopg2.connect(
    host='localhost',
    dbname='postgres',
    user='postgres',
    password='1234',
    port=5432,
    ) as conn:
    with conn.cursor() as cur:
        cur.execute("INSERT INTO news_id (news_id, press_name) VALUES ('6', '매일경제')")

### pymysql

설치

```cmd
pip install pymysql
```
<br>

사용법
```python
conn = pymysql.connect(
  host='address',
  db='database name',
  user='user name',
  password='password',
  port=port,
  charset='utf8',
  autocommit=True,                          # optional, update, delete시 자동 commit
  cursorclass=pymysql.cursors.DictCursor,   # optional, db조회 시 결과를 dictionary로 반환
)

cur = conn.cursor()
```

<br>

CRUD
```python
cur.execute(f'INSERT INTO test (id, press_name) VALUES ({id}, {press_name});')
conn.commit() # CREATE

cur.execute('SELECT * FROM test;')
result_one = cur.fetchone() # READ
result_many = cur.fetchmany() 
result_all = cur.fetchall() 

cur.execute(f'UPDATE test SET press_name={press_name} WHERE id > 5')
conn.commit() # UPDATE

cur.execute('DELETE FROM test WHERE press_name LIKE %조선%;')
conn.commit() # DELETE
```
<br>

pandas 내의 method를 통해서도 사용 가능
```python
pd.read_sql('SELECT * FROM test', conn)
```
<br>

Closer <br>
사용 후 연결 해제 <br>
```python
conn.close()
```
<br>

아래와 같이 사용 가능
```python
with conn.cursor() as cur:
  cur.execute(query)

conn.close()

with pymysql.connect():
  with conn.cursor() as cur:
    cur.execute(query)
```

### sqlalchemy

설치
```cmd
pip install sqlalchemy
```
<br>

사용법

```python
from sqlalchemy import create_engine
from sqlalchemy.types import Integer, Text, String, DateTime

# postgresql
db_url = f'postgres+psycopg2://{USERNAME}:{PASSWORD}@{DB_HOST}:{PORT}/{DB_NAME}'
# mysql

db_url = f'mysql+pymysql://{USERNAME}:{PASSWORD}@{DB_HOST}:{PORT}/{DB_NAME}'
engine = create_engine(db_url, echo=True)

test.to_sql(
  'schema',
  engine,
  if_exists='append', # replace: 덮어쓰기
  index=False,
  chunksize=5000,
  dtypes={              # optinal
    'id': Integer,
    'press_name': Text
  }
)
```

In [52]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.types import Integer, Text, String, DateTime

In [43]:
USERNAME = 'postgres'
PASSWORD = '1234'
DB_HOST = 'localhost'
PORT = 5432
DB_NAME = 'postgres'

db_url = f'postgresql+psycopg2://{USERNAME}:{PASSWORD}@{DB_HOST}:{PORT}/{DB_NAME}'
engine = create_engine(db_url, echo=True)

conn = psycopg2.connect(
    host='localhost',
    dbname='postgres',
    user='postgres',
    password='1234',
    port=5432,
)

In [44]:
pd.read_sql('SELECT * FROM news_id', conn)

C:\Users\USER\AppData\Local\Temp\ipykernel_728\2234271291.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('SELECT * FROM news_id', conn)

  news_id press_name
0       ３       동앙일보
1       ４       연합뉴스
2       ２       중앙일보
3       １       조선일보
4       6       매일경제

In [51]:
temp = pd.DataFrame({
    'a': [1, 2, 3, 4],
    'b': [5, 6, 7, 8]
})

temp.to_sql(
    'public',
    con=engine,
    if_exists='append',
    index=False,
    dtypes={
        'id': Integer,
        'press_name': Text
    }
)

2024-08-16 16:50:04,431 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-08-16 16:50:04,434 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2024-08-16 16:50:04,436 INFO sqlalchemy.engine.Engine [cached since 90.1s ago] {'table_name': 'public', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2024-08-16 16:50:04,441 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2024-08-16 16:50:04,442 INFO sqlalchemy.engine.Engine [cached since 90.11s ago] {'table_name': 'public', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2024-08-16 16:50:04,447 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2024-08-16 16:50:04,448 INFO sqlalchemy.engine.Engine [generated in 0.00108s] {'param_1': 'r', 'param_2': 'p', 'relpersistence_1': 't', 'nspname_1': 'pg_catalog'}
2024-08-16 16:50:04,455 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2024-08-16 16:50:04,457 INFO sqlalchemy.engine.Engine [generated in 0.00130s] {'param_1': 'v', 'relpersistence_1': 't', 'nspname_1': 'pg_catalog'}
2024-08-16 16:50:04,460 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2024-08-16 16:50:04,461 INFO sqlalchemy.engine.Engine [cached since 0.005564s ago] {'param_1': 'm', 'relpersistence_1': 't', 'nspname_1': 'pg_catalog'}
2024-08-16 16:50:04,469 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_attribute.attname AS name, pg_catalog.format_type(pg_catalog.pg_attribute.atttypid, pg_catalog.pg_attribute.atttypmod) AS format_type, (SELECT pg_catalog.pg_get_expr(pg_catalog.pg_attrdef.adbin, pg_catalog.pg_attrdef.adrelid) AS pg_get_expr_1
FROM pg_catalog.pg_attrdef
WHERE pg_catalog.pg_attrdef.adrelid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attrdef.adnum = pg_catalog.pg_attribute.attnum AND pg_catalog.pg_attribute.atthasdef) AS "default", pg_catalog.pg_attribute.attnotnull AS not_null, pg_catalog.pg_class.relname AS table_name, pg_catalog.pg_description.description AS comment, pg_catalog.pg_attribute.attgenerated AS generated, (SELECT json_build_object(%(json_build_object_2)s, pg_catalog.pg_attribute.attidentity = %(attidentity_1)s, %(json_build_object_3)s, pg_catalog.pg_sequence.seqstart, %(json_build_object_4)s, pg_catalog.pg_sequence.seqincrement, %(json_build_object_5)s, pg_catalog.pg_sequence.seqmin, %(json_build_object_6)s, pg_catalog.pg_sequence.seqmax, %(json_build_object_7)s, pg_catalog.pg_sequence.seqcache, %(json_build_object_8)s, pg_catalog.pg_sequence.seqcycle) AS json_build_object_1
FROM pg_catalog.pg_sequence
WHERE pg_catalog.pg_attribute.attidentity != %(attidentity_2)s AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog.pg_get_serial_sequence(CAST(CAST(pg_catalog.pg_attribute.attrelid AS REGCLASS) AS TEXT), pg_catalog.pg_attribute.attname) AS REGCLASS) AS OID)) AS identity_options
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_attribute ON pg_catalog.pg_class.oid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attribute.attnum > %(attnum_1)s AND NOT pg_catalog.pg_attribute.attisdropped LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_description.objsubid = pg_catalog.pg_attribute.attnum JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_attribute.attnum
2024-08-16 16:50:04,469 INFO sqlalchemy.engine.Engine [generated in 0.00074s] {'json_build_object_2': 'always', 'attidentity_1': 'a', 'json_build_object_3': 'start', 'json_build_object_4': 'increment', 'json_build_object_5': 'minvalue', 'json_build_object_6': 'maxvalue', 'json_build_object_7': 'cache', 'json_build_object_8': 'cycle', 'attidentity_2': '', 'attnum_1': 0, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'public'}
2024-08-16 16:50:04,475 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_type.typname AS name, pg_catalog.format_type(pg_catalog.pg_type.typbasetype, pg_catalog.pg_type.typtypmod) AS attype, NOT pg_catalog.pg_type.typnotnull AS nullable, pg_catalog.pg_type.typdefault AS "default", pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, domain_constraints.condefs, domain_constraints.connames, pg_catalog.pg_collation.collname
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN pg_catalog.pg_collation ON pg_catalog.pg_type.typcollation = pg_catalog.pg_collation.oid LEFT OUTER JOIN (SELECT pg_catalog.pg_constraint.contypid AS contypid, array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s)) AS condefs, array_agg(CAST(pg_catalog.pg_constraint.conname AS TEXT)) AS connames
FROM pg_catalog.pg_constraint
WHERE pg_catalog.pg_constraint.contypid != %(contypid_1)s GROUP BY pg_catalog.pg_constraint.contypid) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid
WHERE pg_catalog.pg_type.typtype = %(typtype_1)s ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
2024-08-16 16:50:04,476 INFO sqlalchemy.engine.Engine [generated in 0.00093s] {'pg_get_constraintdef_1': True, 'contypid_1': 0, 'typtype_1': 'd'}
2024-08-16 16:50:04,482 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_type.typname AS name, pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, lbl_agg.labels AS labels
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN (SELECT pg_catalog.pg_enum.enumtypid AS enumtypid, array_agg(CAST(pg_catalog.pg_enum.enumlabel AS TEXT) ORDER BY pg_catalog.pg_enum.enumsortorder) AS labels
FROM pg_catalog.pg_enum GROUP BY pg_catalog.pg_enum.enumtypid) AS lbl_agg ON pg_catalog.pg_type.oid = lbl_agg.enumtypid
WHERE pg_catalog.pg_type.typtype = %(typtype_1)s ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
2024-08-16 16:50:04,482 INFO sqlalchemy.engine.Engine [generated in 0.00089s] {'typtype_1': 'e'}
2024-08-16 16:50:04,487 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.oid, pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s)
2024-08-16 16:50:04,487 INFO sqlalchemy.engine.Engine [generated in 0.00081s] {'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'public'}
2024-08-16 16:50:04,493 INFO sqlalchemy.engine.Engine SELECT attr.conrelid, array_agg(CAST(attr.attname AS TEXT) ORDER BY attr.ord) AS cols, attr.conname, min(attr.description) AS description, NULL AS extra
FROM (SELECT con.conrelid AS conrelid, con.conname AS conname, con.conindid AS conindid, con.description AS description, con.ord AS ord, pg_catalog.pg_attribute.attname AS attname
FROM pg_catalog.pg_attribute JOIN (SELECT pg_catalog.pg_constraint.conrelid AS conrelid, pg_catalog.pg_constraint.conname AS conname, pg_catalog.pg_constraint.conindid AS conindid, unnest(pg_catalog.pg_constraint.conkey) AS attnum, generate_subscripts(pg_catalog.pg_constraint.conkey, %(generate_subscripts_1)s) AS ord, pg_catalog.pg_description.description AS description
FROM pg_catalog.pg_constraint LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid
WHERE pg_catalog.pg_constraint.contype = %(contype)s AND pg_catalog.pg_constraint.conrelid IN (%(oids_1)s)) AS con ON pg_catalog.pg_attribute.attnum = con.attnum AND pg_catalog.pg_attribute.attrelid = con.conrelid
WHERE con.conrelid IN (%(oids_1)s)) AS attr GROUP BY attr.conrelid, attr.conname ORDER BY attr.conrelid, attr.conname
2024-08-16 16:50:04,494 INFO sqlalchemy.engine.Engine [generated in 0.00135s] {'generate_subscripts_1': 1, 'contype': 'p', 'oids_1': 24580}
2024-08-16 16:50:04,500 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname, CASE WHEN (pg_catalog.pg_constraint.oid IS NOT NULL) THEN pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s) END AS anon_1, nsp_ref.nspname, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_class.oid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_constraint.contype = %(contype_1)s LEFT OUTER JOIN pg_catalog.pg_class AS cls_ref ON cls_ref.oid = pg_catalog.pg_constraint.confrelid LEFT OUTER JOIN pg_catalog.pg_namespace AS nsp_ref ON cls_ref.relnamespace = nsp_ref.oid LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname
2024-08-16 16:50:04,501 INFO sqlalchemy.engine.Engine [generated in 0.00095s] {'pg_get_constraintdef_1': True, 'contype_1': 'f', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'public'}
2024-08-16 16:50:04,508 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_index.indrelid, cls_idx.relname AS relname_index, pg_catalog.pg_index.indisunique, pg_catalog.pg_constraint.conrelid IS NOT NULL AS has_constraint, pg_catalog.pg_index.indoption, cls_idx.reloptions, pg_catalog.pg_am.amname, CASE WHEN (pg_catalog.pg_index.indpred IS NOT NULL) THEN pg_catalog.pg_get_expr(pg_catalog.pg_index.indpred, pg_catalog.pg_index.indrelid) END AS filter_definition, pg_catalog.pg_index.indnkeyatts, pg_catalog.pg_index.indnullsnotdistinct, idx_cols.elements, idx_cols.elements_is_expr
FROM pg_catalog.pg_index JOIN pg_catalog.pg_class AS cls_idx ON pg_catalog.pg_index.indexrelid = cls_idx.oid JOIN pg_catalog.pg_am ON cls_idx.relam = pg_catalog.pg_am.oid LEFT OUTER JOIN (SELECT idx_attr.indexrelid AS indexrelid, min(idx_attr.indrelid) AS min_1, array_agg(idx_attr.element ORDER BY idx_attr.ord) AS elements, array_agg(idx_attr.is_expr ORDER BY idx_attr.ord) AS elements_is_expr
FROM (SELECT idx.indexrelid AS indexrelid, idx.indrelid AS indrelid, idx.ord AS ord, CASE WHEN (idx.attnum = %(attnum_1)s) THEN pg_catalog.pg_get_indexdef(idx.indexrelid, idx.ord + %(ord_1)s, %(pg_get_indexdef_1)s) ELSE CAST(pg_catalog.pg_attribute.attname AS TEXT) END AS element, idx.attnum = %(attnum_2)s AS is_expr
FROM (SELECT pg_catalog.pg_index.indexrelid AS indexrelid, pg_catalog.pg_index.indrelid AS indrelid, unnest(pg_catalog.pg_index.indkey) AS attnum, generate_subscripts(pg_catalog.pg_index.indkey, %(generate_subscripts_1)s) AS ord
FROM pg_catalog.pg_index
WHERE NOT pg_catalog.pg_index.indisprimary AND pg_catalog.pg_index.indrelid IN (%(oids_1)s)) AS idx LEFT OUTER JOIN pg_catalog.pg_attribute ON pg_catalog.pg_attribute.attnum = idx.attnum AND pg_catalog.pg_attribute.attrelid = idx.indrelid
WHERE idx.indrelid IN (%(oids_1)s)) AS idx_attr GROUP BY idx_attr.indexrelid) AS idx_cols ON pg_catalog.pg_index.indexrelid = idx_cols.indexrelid LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_index.indrelid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_index.indexrelid = pg_catalog.pg_constraint.conindid AND pg_catalog.pg_constraint.contype = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s])
WHERE pg_catalog.pg_index.indrelid IN (%(oids_1)s) AND NOT pg_catalog.pg_index.indisprimary ORDER BY pg_catalog.pg_index.indrelid, cls_idx.relname
2024-08-16 16:50:04,509 INFO sqlalchemy.engine.Engine [generated in 0.00081s] {'attnum_1': 0, 'ord_1': 1, 'pg_get_indexdef_1': True, 'attnum_2': 0, 'generate_subscripts_1': 1, 'param_1': 'p', 'param_2': 'u', 'param_3': 'x', 'oids_1': 24580}
2024-08-16 16:50:04,514 INFO sqlalchemy.engine.Engine SELECT attr.conrelid, array_agg(CAST(attr.attname AS TEXT) ORDER BY attr.ord) AS cols, attr.conname, min(attr.description) AS description, bool_and(pg_catalog.pg_index.indnullsnotdistinct) AS indnullsnotdistinct
FROM (SELECT con.conrelid AS conrelid, con.conname AS conname, con.conindid AS conindid, con.description AS description, con.ord AS ord, pg_catalog.pg_attribute.attname AS attname
FROM pg_catalog.pg_attribute JOIN (SELECT pg_catalog.pg_constraint.conrelid AS conrelid, pg_catalog.pg_constraint.conname AS conname, pg_catalog.pg_constraint.conindid AS conindid, unnest(pg_catalog.pg_constraint.conkey) AS attnum, generate_subscripts(pg_catalog.pg_constraint.conkey, %(generate_subscripts_1)s) AS ord, pg_catalog.pg_description.description AS description
FROM pg_catalog.pg_constraint LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid
WHERE pg_catalog.pg_constraint.contype = %(contype)s AND pg_catalog.pg_constraint.conrelid IN (%(oids_1)s)) AS con ON pg_catalog.pg_attribute.attnum = con.attnum AND pg_catalog.pg_attribute.attrelid = con.conrelid
WHERE con.conrelid IN (%(oids_1)s)) AS attr JOIN pg_catalog.pg_index ON attr.conindid = pg_catalog.pg_index.indexrelid GROUP BY attr.conrelid, attr.conname ORDER BY attr.conrelid, attr.conname
2024-08-16 16:50:04,515 INFO sqlalchemy.engine.Engine [generated in 0.00073s] {'generate_subscripts_1': 1, 'contype': 'u', 'oids_1': 24580}
2024-08-16 16:50:04,518 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_class.oid = pg_catalog.pg_description.objoid AND pg_catalog.pg_description.objsubid = %(objsubid_1)s JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s)
2024-08-16 16:50:04,519 INFO sqlalchemy.engine.Engine [generated in 0.00075s] {'objsubid_1': 0, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'public'}
2024-08-16 16:50:04,522 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname, CASE WHEN (pg_catalog.pg_constraint.oid IS NOT NULL) THEN pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s) END AS anon_1, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_class.oid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_constraint.contype = %(contype_1)s LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname
2024-08-16 16:50:04,523 INFO sqlalchemy.engine.Engine [generated in 0.00065s] {'pg_get_constraintdef_1': True, 'contype_1': 'c', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'public'}
2024-08-16 16:50:04,525 INFO sqlalchemy.engine.Engine
DROP TABLE public
2024-08-16 16:50:04,525 INFO sqlalchemy.engine.Engine [no key 0.00057s] {}
2024-08-16 16:50:04,528 INFO sqlalchemy.engine.Engine
CREATE TABLE public (
	a BIGINT,
	b BIGINT
)


2024-08-16 16:50:04,529 INFO sqlalchemy.engine.Engine [no key 0.00061s] {}
2024-08-16 16:50:04,533 INFO sqlalchemy.engine.Engine INSERT INTO public (a, b) VALUES (%(a__0)s, %(b__0)s), (%(a__1)s, %(b__1)s), (%(a__2)s, %(b__2)s), (%(a__3)s, %(b__3)s)
2024-08-16 16:50:04,535 INFO sqlalchemy.engine.Engine [generated in 0.00017s (insertmanyvalues) 1/1 (unordered)] {'b__0': 5, 'a__0': 1, 'b__1': 6, 'a__1': 2, 'b__2': 7, 'a__2': 3, 'b__3': 8, 'a__3': 4}
2024-08-16 16:50:04,539 INFO sqlalchemy.engine.Engine COMMIT

4

### pymongo

설치

```bash
pip install pymongo
```
<br>

사용법
```python
from pymongo import MongoClient

# 방법1. URI
uri = f'mongodb://{user_name}:{password}@{host}:{port}/{db_name}?authSource=admin'
client = MongoClient(uri)

# 방법2. parameter
client = MongoClient(
    host='localhost',
    port=27017,    
)

db = client['*database_name*']
collection = db['*collection_name*']
```

<br>

<span style='font-size: 18px'> DB 및 Collection 관련 커맨드 </span>

```python
client.list_database_names()                # database 조회
client.drop_database('*database name*')     # database 제거
db.list_collection_names()                  # collection 조회
db.drop_collection('*collection name*')     # collection 제거
```

<br>

<span style='font-size: 18px'> Create </span>

```python
# 단일 문서 삽입
result = *collection_name*.insert_one({'name': 'Alice', 'age': 25})

# 다수의 문서 삽입
result = *collection_name*.insert_many([{'name': 'Bob', 'age': 30}, {'name': 'Charlie', 'age': 35}])
```

<br>

<span style='font-size: 18px'> Read </span>

```python
# 단일 문서 조회
document = *collection_name*.find_one({'name': 'Alice'})

# 여러 문서 조회
documents = *collection_name*.find({'age': {'$gt': 25}})
```

<br>

<span style='font-size: 18px'> Update </span>

```python
# 단일 문서 업데이트
result = *collection_name*.update_one({'name': 'Alice'}, {'$set': {'age': 26}})

# 여러 문서 업데이트
result = *collection_name*.update_many({'age': {'$lt': 30}}, {'$set': {'status': 'young'}})
```

<br>

<span style='font-size: 18px'> Delete </span>

```python
# 단일 문서 삭제
result = *collection_name*.delete_one({'name': 'Alice'})

# 여러 문서 삭제
result = *collection_name*.delete_many({'age': {'$lt': 30}})
```

In [53]:
import pymongo

In [54]:
client = pymongo.MongoClient(
    host='localhost',
    port=27017,
)

In [56]:
database = client['news']
collection = database['news_id']

In [57]:
# use news
# db.news_id
collection.insert_one({'news_id': 6, 'press_name': '매일경제'})

InsertOneResult(ObjectId('66bf08e5cf4f7332a32f9962'), acknowledged=True)

In [58]:
collection.insert_many([
    {'news_id': 1, 'press_name': '조선일보'},
    {'news_id': 2, 'press_name': '중앙일보'},
    {'news_id': 3, 'press_name': '동아일보'},
    {'news_id': 4, 'press_name': '연합뉴스'},
    ])

InsertManyResult([ObjectId('66bf0969cf4f7332a32f9963'), ObjectId('66bf0969cf4f7332a32f9964'), ObjectId('66bf0969cf4f7332a32f9965'), ObjectId('66bf0969cf4f7332a32f9966')], acknowledged=True)

In [65]:
list(collection.aggregate([{'$match': {'news_id': {'$gte': 3}}}]))

[{'_id': ObjectId('66bf08e5cf4f7332a32f9962'),
  'news_id': 6,
  'press_name': '매일경제'},
 {'_id': ObjectId('66bf0969cf4f7332a32f9965'),
  'news_id': 3,
  'press_name': '동아일보'},
 {'_id': ObjectId('66bf0969cf4f7332a32f9966'),
  'news_id': 4,
  'press_name': '연합뉴스'}]

In [64]:
for temp in collection.aggregate([{'$match': {'news_id': {'$gte': 3}}}]):
    print(temp)

{'_id': ObjectId('66bf08e5cf4f7332a32f9962'), 'news_id': 6, 'press_name': '매일경제'}
{'_id': ObjectId('66bf0969cf4f7332a32f9965'), 'news_id': 3, 'press_name': '동아일보'}
{'_id': ObjectId('66bf0969cf4f7332a32f9966'), 'news_id': 4, 'press_name': '연합뉴스'}

## Database Link to Streamlit

.streamlit 생성 -> secrets.toml 생성 후 연결하고자 하는 DB에 따라 secrets.toml에 내용 추가 <br>

### postgres

<span style="font-size: 18px;">secrets.toml</span>

```
[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "xxx"
username = "xxx"
password = "xxx"
```

<br>

<span style="font-size: 18px;">python script</span>


```python
import streamlit as st

conn = st.connection("postgresql", type="sql")
df = conn.query('SELECT * FROM *table_name*', ttl=600)
```

### mysql

<span style="font-size: 18px;">secrets.toml</span>

```
[connections.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "xxx"
username = "xxx"
password = "xxx"
query = { charset = "xxx" }
```

<br>

<span style="font-size: 18px;">python script</span>


```python
import streamlit as st

conn = st.connection("mysql", type="sql")
df = conn.query('SELECT * FROM *table_name*', ttl=600)
```

### mongo



<span style="font-size: 18px;">secrets.toml</span>

```
host = "localhost"
port = 27017
username = "xxx"
password = "xxx"
```

<br>

<span style="font-size: 18px;">python script</span>


```python
import streamlit as st

@st.cache_resource
def init_connection():
    return pymongo.MongoClient(**st.secrets["mongo"])

client = init_connection()

@st.cache_data(ttl=600)
def get_data():
    db = client.mydb
    items = db.mycollection.find()
    items = list(items)
    return items
```